services:
  trimly:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://147.93.1.252:8003/trimly/api/v1}
    container_name: trimly-frontend
    ports:
      - "84:80"
    restart: unless-stopped
